spring:
  profiles:
    active: dev
  application:
    name: learn_spring_boot

logging:
  level:
    org:
      springframework: debug

currency-service:
  url: https://deafult.in28minutes.com
  username: 3runo
  key: 3runo

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics"