logging:
  level:
    org:
      springframework: trace


currency-service:
  url: https://dev.in28minutes.com
  username: 3runoDev
  key: dev3runo

devtools:
  restart:
    enabled: true
  livereload:
    enabled: true