spring:
  profiles:
    active: dev
  application:
    name: learn_spring_boot

devtools:
  restart:
    enabled: true
  livereload:
    enabled: true

logging:
  level:
    org:
      springframework: debug

currency-service:
  url: https://deafult.in28minutes.com
  username: 3runo
  key: 3runo